### ISSUE TITLE
Corpus usage request form

### ISSUE THREAD

**Issue by ruanchaves** [HAILab-PUCPR/SemClinBr#1]
I would like to know if there are any plans to make the corpus usage request form available this year ( since this README hasn't been updated in the last seven months ). I belong to a university research group that would be interested in utilizing the dataset for scientific purposes. Thank you.

**Comment by ferrerallan** [comment]
I would like to know if there are any plans to make the corpus usage request form . I belong to a university research group that would be interested in utilizing the dataset for scientific purposes. Thank you.

**Comment by brunovilar** [comment]
I am also interested in requesting access to the corpus.

**Comment by lisaterumi** [comment]
We really appreciate your interest :)

We are awaiting the return of the ethics committee, as soon as we receive the answer, we will publish the corpus.

Best regards

**Comment by luizniero** [comment]
Eu também gostaria de saber se o corpus já está disponível para requisição. Sou aluno de mestrado em ciência da computação e seu trabalho eh o principal dentre os trabalhos correlatos de minha dissertação

**Comment by judsonbsilva** [comment]
Também tenho interesse nesse Corpus. Quando vai estar disponível?

**Comment by luizniero** [comment]
@lisaterumi nenhuma novidade? Eu realmente gostaria de ter acesso ao corpus antes de setembro para o desenvolvimento do meu projeto de mestrado. Caso contrário terei de criar o meu próprio Corpus, o que mudará um pouco o rumo da minha pesquisa.

@lisaterumi no news? I really would to have acess to the corpus before september for the development of my master degree research. Otherwise i will have to make my own corpus, what will change the aim of my searches

**Comment by lisaterumi** [comment]
@kunkaweb Lucas Oliveira alguma notícia sobre o SemClinBr?

**Comment by tutubalinaev** [comment]
any news? could you please tell me how to download this corpus?

**Comment by lisaterumi** [comment]
Hello everyone, the corpus is now available and can be requested. On our readme page (https://github.com/HAILab-PUCPR/SemClinBr), you can have more details.
@ruanchaves  @ferrerallan @brunovilar @luizniero @tutubalinaev @judsonbsilva
Thank you.
